export const books = [
  {
    id: 1,
    title: "Atomic One's",
    price: "$ 13.84 USD",
    imageName: "hero-img2",
    alt: "Atomic One's",
    category: "Fiction",
  },
  {
    id: 2,
    title: "The Dark Light",
    price: "$ 86.11 USD",
    imageName: "hero-img3",
    alt: "The Dark Light",
    category: "Fiction",
  },
  {
    id: 3,
    title: "The Great Toolkit",
    price: "$ 45.99 USD",
    imageName: "hero-img",
    alt: "The Great Toolkit",
    category: "Non-Fiction",
  },
  {
    id: 4,
    title: "Women's Life",
    price: "$ 32.50 USD",
    imageName: "hero-img2",
    alt: "Women's Life",
    category: "Non-Fiction",
  },
  {
    id: 5,
    title: "Children's Dreams",
    price: "$ 19.99 USD",
    imageName: "hero-img3",
    alt: "Children's Dreams",
    category: "Children",
  },
  {
    id: 6,
    title: "Science Today",
    price: "$ 54.99 USD",
    imageName: "hero-img",
    alt: "Science Today",
    category: "Academic",
  },
  {
    id: 7,
    title: "The Midnight Library",
    price: "$ 24.99 USD",
    imageName: "hero-img2",
    alt: "The Midnight Library",
    category: "Fiction",
  },
  {
    id: 8,
    title: "Atomic Habits",
    price: "$ 18.99 USD",
    imageName: "hero-img3",
    alt: "Atomic Habits",
    category: "Non-Fiction",
  },
  {
    id: 9,
    title: "Where the Crawdads Sing",
    price: "$ 28.99 USD",
    imageName: "hero-img",
    alt: "Where the Crawdads Sing",
    category: "Fiction",
  },
  {
    id: 10,
    title: "The Silent Patient",
    price: "$ 15.99 USD",
    imageName: "hero-img2",
    alt: "The Silent Patient",
    category: "Fiction",
  },
  {
    id: 11,
    title: "Educated",
    price: "$ 22.99 USD",
    imageName: "hero-img3",
    alt: "Educated",
    category: "Non-Fiction",
  },
  {
    id: 12,
    title: "Becoming",
    price: "$ 29.99 USD",
    imageName: "hero-img",
    alt: "Becoming",
    category: "Non-Fiction",
  },
]
